--nnoremap <F1> :pclose<CR>:silent YcmCompleter GetDoc<CR>
--nnoremap <S-F1> :pclose<CR>
--nnoremap <C-F1> :YcmCompleter GetType<CR>
--nnoremap <F9> :YcmCompleter GoTo<CR>
--nnoremap <S-F9> :YcmCompleter GoToReferences<CR>
--nnoremap <F10> :YcmCompleter FixIt<CR>
